// src/components/main/distance/DistanceEntryComponent.svelte
<script lang="ts">
	import type { Distance } from '../../../models';

	export let distance: number;
	export let unit: Distance.Unit;

	export let toggleUnit: () => void;

	$: displayUnit = unit === 'm' ? 'MILES' : 'KILOMETERS';
</script>

<div>
	<div class="input-holder">
		<input type="number" bind:value={distance} />
	</div>
	<div class="unit-holder">
		<div class="unit" on:click={toggleUnit}>{displayUnit}</div>
	</div>
</div>

// archive/v3-gatsby/src/components/main/1-distance/distance-entry/index.tsx
import { Distance } from 'models';
import React, { FC, useState } from 'react';

import * as Style from './style.module.scss';

type DistanceEntryComponentProps = {
  distance: number;
  setDistance: (d: number) => void;
  unit: 'm' | 'k';
  toggleUnit: () => void;
}

export const DistanceEntryComponent: FC<DistanceEntryComponentProps> = ({
  distance,
  setDistance,
  unit,
  toggleUnit
}) => {

  const displayUnit = (unit === 'm') ? 'MILES' : 'KILOS';

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setDistance(parseFloat(e.target.value));
  }

  return (
    <table id="dist-table">
      <tr>
        <td id="dist-input-td">
          <input type="number" id="dist-num" onChange={handleChange} value={distance} />
        </td>
        {/* ontouchstart="event.preventDefault();toggleUnit();" */}
        <td id="dist-unit-td" onClick={toggleUnit}>{displayUnit}</td>
        <td className="gap"></td>
      </tr>
    </table>
  );
}
