// archive/v3-gatsby/src/components/main/index.tsx
import React, { FC, useState } from 'react';
// import { useQueryParam, StringParam } from "use-query-params";

import { Time } from 'models';
// import { } from 'elements';

import { HeaderComponent } from './0-header';
import { DistanceComponent } from './1-distance';
import { TimeInputComponent } from './2-time-in';
import { SplitComponent } from './3-split';
import { TimeOutputComponent } from './4-time-out';
// import { AdComponent } from './5-ad';
import * as Style from './style.module.scss';

export const MainComponent: FC = () => {

  // distance
  const [raceName, setRaceName] = useState<string>('5K');
  const [distanceMode, setDisanceMode] = useState<boolean>(false);
  const [distance, setDistance] = useState<number>(0);
  const [unit, setUnit] = useState<'m' | 'k'>('m');

  // time
  const [timeIn, setTimeIn] = useState<number>(0);

  // split
  const [splitName, setSplitName] = useState<string>('MILE');
  const [paceMode, setPaceMode] = useState<boolean>(false);

  // TODO: load data from url params
  // TODO: store cookies based on input

  const toggleUnit = () => {
    switch (unit) {
      case 'm':
        setUnit('k');
        break;
      case 'k':
      default:
        setUnit('m');
    };
  };

  const timeOut = Time.calcTime({
    timeIn,
    raceName,
    distance,
    distanceMode,
    splitName,
    paceMode,
    unit
  });

  return (
    <main className={Style.app}>
      <div className={Style.container}>
        <HeaderComponent />
        <DistanceComponent
          raceName={raceName}
          setRaceName={(n: string) => setRaceName(n)}
          distance={distance}
          setDistance={(d: number) => setDistance(d)}
          distanceMode={distanceMode}
          toggleDistanceMode={() => setDisanceMode(!distanceMode)}
          unit={unit}
          toggleUnit={toggleUnit}
        />
        <TimeInputComponent
          timeIn={timeIn}
          setTimeIn={(t: number) => setTimeIn(t)}
          paceMode={paceMode}
          togglePaceMode={() => setPaceMode(!paceMode)}
        />
        <SplitComponent
          splitName={splitName}
          setSplitName={(n: string) => setSplitName(n)}
        />
        <TimeOutputComponent
          timeOut={timeOut}
        />
        {/* <AdComponent /> */}
      </div>
    </main>
  )
}

// src/components/MainComponent.svelte
<script lang="ts">
	import { Distance, Time } from '../models';

	import HeaderComponent from './main/HeaderComponent.svelte';
	import DistanceComponent from './main/DistanceComponent.svelte';
	import TimeInputComponent from './main/TimeInputComponent.svelte';
	import SplitComponent from './main/SplitComponent.svelte';
	import TimeOutputComponent from './main/TimeOutputComponent.svelte';

	// distance
	type distanceDataType = {
		race: Distance.Event;
		distanceMode: boolean;
		distance: number;
		unit: Distance.Unit;
	};
	let distanceData: distanceDataType = {
		race: Distance.getEvent('5K'),
		distanceMode: false,
		distance: 0,
		unit: 'm'
	};

	const setRace = (event: Distance.Event) => {
		distanceData.race = event;
	};

	// time
	let timeIn = 0;
	let paceMode = false;

	// split
	let split = Distance.getEvent('MILE');

	const toggleUnit = () => {
		distanceData.unit =
			{
				m: 'k' as Distance.Unit,
				k: 'm' as Distance.Unit
			}[distanceData.unit] || 'm';
	};

	const addTime = (deltaSeconds: number) => {
		timeIn = timeIn + deltaSeconds;
	};

	$: timeOut = Time.calcTime({
		split,
		timeIn,
		paceMode,
		...distanceData
	});
</script>

<!-- HTML -->
<main class="app">
	<div class="container">
		<HeaderComponent />
		<DistanceComponent
			{...distanceData}
			toggleDistanceMode={() => (distanceData.distanceMode = !distanceData.distanceMode)}
			{toggleUnit}
			{setRace}
		/>
		<TimeInputComponent
			{addTime}
			{timeIn}
			{paceMode}
			togglePaceMode={() => (paceMode = !paceMode)}
		/>
		<SplitComponent {split} />
		<TimeOutputComponent {timeOut} />
		<!-- {/* <AdComponent /> */} -->
	</div>
</main>

<style lang="scss">
	.app {
		width: 100%;
		height: 100%;

		.container {
			margin: 0 auto;
			height: 100%;
			width: 100%;
		}
	}
</style>
